version: '3'
services:
  mitmproxy:
    image: mitmproxy/mitmproxy
    command: >
      bash -c "apt-get update &&
               apt-get install -y procps &&
               /bin/bash"
    volumes:
      - ./scripts:/home/mitmproxy/scripts
    stdin_open: true
    tty: true
