version: '3'
services:
  mitmproxy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./scripts:/home/mitmproxy/scripts
      - ./mitmproxy-keys:/home/mitmproxy/.mitmproxy
      - ./override-files:/home/mitmproxy/override-files
    command: /bin/bash
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
